apiVersion: v1
kind: Pod
metadata:
  name: longhorn-test
  namespace: longhorn-smoke-test
spec:
  containers:
    - name: test
      image: busybox:1.37.0
      command:
        - sh
        - -c
        - echo 'Longhorn smoke-test pod started'; sleep infinity
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: longhorn-test
