apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: juicefs-postgres
  namespace: postgres
spec:
  instances: 3

  imageName: ghcr.io/cloudnative-pg/postgresql:16

  primaryUpdateStrategy: unsupervised

  storage:
    size: 20Gi
    storageClass: local-path

  bootstrap:
    initdb:
      database: juicefs
      owner: juicefs
      secret:
        name: juicefs-db-auth

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"
