apiVersion: v1
kind: Secret
metadata:
  name: juicefs-secret
  namespace: juicefs
  labels:
    juicefs.com/validate-secret: "true"
type: Opaque
stringData:
  name: jfs-office
  metaurl: postgres://juicefs:JuiceFSDB%40123456@juicefs-postgres-rw.postgres.svc.cluster.local:5432/juicefs?sslmode=disable
  storage: s3
  bucket: http://minio.minio.svc.cluster.local:9000/juicefs
  access-key: minioadmin
  secret-key: MinioAdmin@123456
  envs: "{TZ: Asia/Shanghai}"
  format-options: "trash-days=7"
