apiVersion: v1
kind: Secret
metadata:
  name: juicefs-secret
  namespace: juicefs
type: Opaque
stringData:
  name: jfs-office

  metaurl: "postgres://juicefs:JuiceFSDB%40123456@192.168.13.215:5432/juicefs?sslmode=disable"

  storage: s3

  bucket: "http://192.168.13.210:9000/juicefs"

  access-key: "minioadmin"

  secret-key: "MinioAdmin@123456"

  envs: "{TZ: Asia/Shanghai}"
