apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edgar-pvc
  namespace: office-storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: juicefs-sc
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: public-pvc
  namespace: office-storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: juicefs-sc
  resources:
    requests:
      storage: 500Gi
