apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: office-files-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: juicefs-sc
  resources:
    requests:
      storage: 500Gi
