apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: team-a-developers
  namespace: team-a
  labels:
    managed-by: gitops
subjects:
  - kind: Group
    name: team-a-developers
    apiGroup: rbac.authorization.k8s.io

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: developer