apiVersion: v1
kind: Secret
metadata:
  name: metallb-prometheus-token
  namespace: metallb-system
  annotations:
    kubernetes.io/service-account.name: kube-prometheus-stack-prometheus
type: kubernetes.io/service-account-token
