apiVersion: v1
kind: ServiceAccount
metadata:
  name: metallb-prometheus
  namespace: metallb-system
---
apiVersion: v1
kind: Secret
metadata:
  name: metallb-prometheus-token
  namespace: metallb-system
  annotations:
    kubernetes.io/service-account.name: metallb-prometheus
type: kubernetes.io/service-account-token
