apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-dns-harbor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  jobName: blackbox-dns-harbor
  interval: 60s
  scrapeTimeout: 10s
  module: dns_harbor
  prober:
    url: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - 10.43.0.10:53
