replicas: 1

extraSecretMounts:
  - name: snmp-exporter-config
    mountPath: /run/secrets/snmp-exporter
    secretName: snmp-exporter-config
    readOnly: true

extraArgs:
  - --config.file=/etc/snmp_exporter/snmp.yml
  - --config.file=/run/secrets/snmp-exporter/snmp.yml

serviceMonitor:
  enabled: true

  module:
    - if_mib

  auth:
    - spine04_v2

  scrapeTimeout: 10s

  params:
    - name: spine04
      target: 192.168.10.8
      module:
        - if_mib
      labels:
        release: kube-prometheus-stack
      interval: 30s
      scrapeTimeout: 10s
      additionalMetricsRelabels:
        switch: Spine04

    - name: leaf02
      target: 192.168.10.6
      module:
        - if_mib
      labels:
        release: kube-prometheus-stack
      interval: 30s
      scrapeTimeout: 10s
      additionalMetricsRelabels:
        switch: Leaf02

    - name: spine03
      target: 192.168.10.7
      module:
        - if_mib
      labels:
        release: kube-prometheus-stack
      interval: 30s
      scrapeTimeout: 10s
      additionalMetricsRelabels:
        switch: Spine03

    - name: spine01
      target: 192.168.10.3
      module:
        - if_mib
      labels:
        release: kube-prometheus-stack
      interval: 30s
      scrapeTimeout: 10s
      additionalMetricsRelabels:
        switch: Spine01

    - name: leaf01
      target: 192.168.10.9
      module:
        - if_mib
      labels:
        release: kube-prometheus-stack
      interval: 30s
      scrapeTimeout: 10s
      additionalMetricsRelabels:
        switch: Leaf01

    - name: spine02
      target: 192.168.10.4
      module:
        - if_mib
      labels:
        release: kube-prometheus-stack
      interval: 30s
      scrapeTimeout: 20s
      additionalMetricsRelabels:
        switch: Spine02

    - name: core01
      target: 192.168.10.2
      module:
        - if_mib
      labels:
        release: kube-prometheus-stack
      interval: 30s
      scrapeTimeout: 10s
      additionalMetricsRelabels:
        switch: Core01
