apiVersion: v1
kind: Secret
metadata:
  name: mattermost-db
  namespace: mattermost
type: Opaque
stringData:
  DB_CONNECTION_STRING: "postgres://mattermost:CHANGE_ME_STRONG_PASSWORD@mattermost-postgres-rw.mattermost.svc.cluster.local:5432/mattermost?sslmode=require"
